[package]
name = "toyterm"
version = "0.1.0"
authors = ["algon-320 <algon.0320@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.15"
lazy_static = "1.4.0"

[dependencies.sdl2]
git = "https://github.com/Rust-SDL2/rust-sdl2"
default-features = false
features = ["ttf"]
