[general]
# if the 'shell' field is empty, $SHELL is used instead
shell = "/usr/bin/bash" # path to shell
shell_args = ["--noprofile", "--norc"] # arguments passed to the shell
columns = 80
rows = 24


[color_scheme]
# original theme
black = [15, 15, 15]
red = [159, 53, 58]
yellow = [202, 122, 44]
green = [131, 138, 45]
blue = [0, 137, 167]
magenta = [94, 61, 80]
cyan = [79, 114, 108]
white = [189, 192, 186]
gray = [55, 60, 56]
light_red = [199, 62, 58]
light_yellow = [239, 187, 36]
light_green = [190, 194, 63]
light_blue = [46, 169, 223]
light_magenta = [152, 109, 178]
light_cyan = [120, 194, 196]
light_white = [252, 250, 242]


[font]
regular = "monospace"
bold = "monospace"
# the width of half-width char (in pixel)
size = 10
