#!/bin/bash

echo -en '\e[30mk\e[m '
echo -en '\e[31mr\e[m '
echo -en '\e[32mg\e[m '
echo -en '\e[33my\e[m '
echo -en '\e[34mb\e[m '
echo -en '\e[35mm\e[m '
echo -en '\e[36mc\e[m '
echo -en '\e[37mw\e[m '
echo -en '\e[39md\e[m '
echo -en '\e[70m@\e[m '
echo -e  ''

echo -en '\e[40m \e[m '
echo -en '\e[41m \e[m '
echo -en '\e[42m \e[m '
echo -en '\e[43m \e[m '
echo -en '\e[44m \e[m '
echo -en '\e[45m \e[m '
echo -en '\e[46m \e[m '
echo -en '\e[47m \e[m '
echo -en '\e[49m \e[m '
echo -en '\e[80m \e[m '
echo -e  ''
echo -e  ''

echo -e '\\e[1m: \e[1mbold\e[m'
echo -e '\\e[2m: \e[2mfaint\e[m'
echo -e '\\e[3m: \e[3mitalicized\e[m'
echo -e '\\e[4m: \e[4msingly underlined\e[m'
echo -e '\\e[5m: \e[5mslowly blinking\e[m'
echo -e '\\e[6m: \e[6mrapidly blinking\e[m'
echo -e '\\e[7m: \e[7mnegative\e[m'
echo -e '\\e[8m: \e[8mconcealed\e[m (concealed)'
echo -e '\\e[9m: \e[9mcrossed-out\e[m'
